version: '3.7'

services:

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - wavechat-dev
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data  
    restart: always

  s3storagetest:
    container_name: 'storage-test'

    image: 'kovshik/storage-test:dev'

    build:
      context: .
      dockerfile: './S3StorageTest/Dockerfile'
    depends_on:
      - minio
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - wavechat-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - MINIO_HOST=192.168.44.76
      - MINIO_PORT=9000
      - MINIO_USER=masoud
      - MINIO_PASSWORD=Strong#Pass#2022
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro



volumes:
  minio_storage: {}
networks:
   wavechat-dev:
    driver: bridge